### ISSUE TITLE
Console command "migrate/down all" not working as expected

### ISSUE THREAD

**Issue by uagrace** [dmstr/yii2-migrate-command#15]
```
yii migrate/down all
Yii Migration Tool (based on Yii v2.0.8-dev)

Database Connection: mysql:host=localhost;dbname=yii2test
Error: The step argument must be greater than 0.
```

**Comment by schmunk42** [comment]
Thank you for reporting.

Do you know since when `all` is supported? I'm just curios, because I didn't even know that this option exists.

There's still an issue at the core repo about multiple migrations https://github.com/yiisoft/yii2/issues/384
I'd rather wait for this to complete, since this extension is based on code which has changed very much in the meantime, but a PR is always welcome.

I think you may use `99999` instead of `all` as a workaround.

**Comment by uagrace** [comment]
Thanks
