### ISSUE TITLE
Yii2 downgraded version

### ISSUE THREAD

**Issue by StalkAlex** [dmstr/yii2-migrate-command#20]
Why this is happened in minor release?  We're using last version 2.0.10, now your package limited it to <=2.0.9.

**Comment by schmunk42** [comment]
Because Yii introduced namespaced migrations in 2.0.10, which may cause issues since the current version of this command can not properly handle them, and there are already extensions using the namespaced syntax. So it's a patch for this extension to prevent breaks.

Here're looooong discussions about this: https://github.com/yiisoft/yii2/issues/13356 https://github.com/yiisoft/yii2/pull/13359

We might create a 0.4.0-beta1, which lifts this constraint to >=2.0.10 - but currently things might break.

WDYT?

**Comment by StalkAlex** [comment]
Looked through discussions you've mentioned above...  We're not using this extension directly but within Phundament CMS, I made a trick now  ```"yiisoft/yii2": "2.0.11 as 2.0.9"```, everything looks functional now. So if you add beta tag, then it should be mirrored in yii2-cms-metapackage too somehow.

**Comment by StalkAlex** [comment]
I tried beta version, it worked the way we used it - apply all migrations from different modules at once. As I understand Yii maintainers aren't going to support this extension, so I have reasonable question I think.
 As samdark said this functionality already implemented in yii core, so if I want to use basic Yii core migrations with the same functionality, what steps should I do to enable them correctly? We're using 4th Phundament template. As I know there is no alias column in basic migrations module.

**Comment by schmunk42** [comment]
There's no actual code change between the current stable and beta. I just lifted the constraint. 
It's beta because this module is totally untested with the new namespaced migration syntax.

It should not matter if you're using it with phd4 (Phundament) or phd5.

Here's an open PR https://github.com/yiisoft/yii2/pull/13359 which would make this extension completely obsolete. The goal is simply to provide support for aliased migrations as a fallback.

**Comment by StalkAlex** [comment]
> There is an existing way of solving the issue with multiple paths — namespaced migrations. The only issue which you correctly highlighted in the pull request is about migrating to namespaces in the middle of the project which is to be thought about and solved one way or another.
> 
> Introducing another way similar to namespaces makes into the core makes no sense from the framework perspective. ...

Sorry, just don't get it. He's talking about another way, if there is another way supported framework now why do I need this extension? Where is the difference and problem? Could you give some explanation? Thank you.

**Comment by schmunk42** [comment]
> He's talking about another way, if there is another way supported by framework now why do I need this extension?

The issues brought up from my side is actually about deprecating this extension or make it obsolete.
But in a "BC-compatible" way, meaning that you still can use all existing yii2-extensions which have migrations, which you need to run from a path or alias.

> Where is the difference and problem? Could you give some explanation?

There's new way of using **namespaced** migrations, but those are problematic to use with the current **aliased** migrations and `--migrationPath`, see https://github.com/dmstr/yii2-migrate-command/issues/19

**Comment by StalkAlex** [comment]
Thank you! Now I understand the problem I think. Your extension provides more convenient and clean solution comparing what Yii proposes to have a separeted migration table for different modules or have one pile of migrations in one table without aliases at all.
