### ISSUE TITLE
Yii 2.0.12

### ISSUE THREAD

**Issue by ghost** [dmstr/yii2-migrate-command#23]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for dmstr/yii2-migrate-command ^0.3.2 -> satisfiable by dmstr/yii2-migrate-command[0.3.2].
    - Conclusion: remove yiisoft/yii2 2.0.12
    - Conclusion: don't install yiisoft/yii2 2.0.12
    - dmstr/yii2-migrate-command 0.3.2 requires yiisoft/yii2 <2.0.10 -> satisfiable by yiisoft/yii2[2.0.6, 2.0.7, 2.0.8, 2.0.9].
    - Can only install one of: yiisoft/yii2[2.0.6, 2.0.12].
    - Can only install one of: yiisoft/yii2[2.0.7, 2.0.12].
    - Can only install one of: yiisoft/yii2[2.0.8, 2.0.12].
    - Can only install one of: yiisoft/yii2[2.0.9, 2.0.12].
    - Installation request for yiisoft/yii2 (locked at 2.0.12, required as ~2.0.6) -> satisfiable by yiisoft/yii2[2.0.12].

**Comment by schmunk42** [comment]
This multiple migration feature is now supported by the Yii 2.0 Framework core.

Due to these changes we still have "only" a beta version of this extensions compatible with 2.0.10 and above. You can either install `^0.4.0-beta2` or remove it and use the core-way to run multiple migrations.

See also http://www.yiiframework.com/doc-2.0/guide-db-migrations.html#namespaced-migrations 

> Since version 2.0.12 the migrationPath property also accepts an array for specifying multiple directories that contain migrations without a namespace. This is mainly added to be used in existing projects which use migrations from different locations. These migrations mainly come from external sources, like Yii extensions developed by other developers, which can not be changed to use namespaces easily when starting to use the new approach.
